### ISSUE TITLE
Allow KBMOD to output search results in a pandas dataframe

### ISSUE THREAD

**Issue by maxwest-uw** [dirac-institute/kbmod#191]
As we get KBMOD (and other moving objects systems) ready for LSST, we should have a more standardized way of outputing the results (as opposed to our current process of dumping all the results into a text file). I propose we use dataframes as they already have a lot of buy in from the scientific community + multiple LINCC projects are making use of them, so we have lot's of domain knowledge to draw on.

**Comment by jeremykubica** [comment]
Closing this in favor of #354, which will redefine the output structure.
