### ISSUE TITLE
KBMOD will not build while installing under Python 3.11

### ISSUE THREAD

**Issue by ColinOrionChandler** [dirac-institute/kbmod#209]
(Carl and Colin reporting)
Installation with Anaconda (via conda-forge or defaults, with or without "conda install cudatoolkit-dev" trick) prevents KBMOD from building via pip install.

@maxwest-uw knows more about this.

**Comment by jeremykubica** [comment]
Resolved with #217

**Comment by jeremykubica** [comment]
217 isn't actually merged yet. Reopening until that happens.

**Comment by DinoBektesevic** [comment]
It was on wait to test manual build with Python 3.11. Closed in https://github.com/dirac-institute/kbmod/pull/217
