### ISSUE TITLE
resolve deprecated void PyEval_InitThreads()

### ISSUE THREAD

**Issue by cchris28** [dirac-institute/kbmod#214]
cmake --build src/kbmod has deprecation warnings

void PyEval_InitThreads() is deprecated

(kbmod) bash-4.2$ cmake --build src/kbmod

Scanning dependencies of target searchcu
[ 20%] Building CUDA object CMakeFiles/searchcu.dir/search/image_kernels.cu.o
[ 40%] Building CUDA object CMakeFiles/searchcu.dir/search/kernels.cu.o
[ 60%] Linking CUDA static library searchcu.cpython-310-x86_64-linux-gnu.so
[ 60%] Built target searchcu
Scanning dependencies of target search
[ 80%] Building CXX object CMakeFiles/search.dir/search/bindings.cpp.o
In file included from /astro/users/cchris28/projects/kbmod/lib/pybind11/include/pybind11/cast.h:16:0,
                 from /astro/users/cchris28/projects/kbmod/lib/pybind11/include/pybind11/attr.h:13,
                 from /astro/users/cchris28/projects/kbmod/lib/pybind11/include/pybind11/pybind11.h:44,
                 from /astro/users/cchris28/projects/kbmod/src/kbmod/search/bindings.cpp:1:
/astro/users/cchris28/projects/kbmod/lib/pybind11/include/pybind11/detail/internals.h: In function ‘pybind11::detail::internals& pybind11::detail::get_internals()’:
/astro/users/cchris28/projects/kbmod/lib/pybind11/include/pybind11/detail/internals.h:200:9: warning: ‘void PyEval_InitThreads()’ is deprecated (declared at /astro/users/cchris28/.conda/envs/kbmod/include/python3.10/ceval.h:122) [-Wdeprecated-declarations]
         PyEval_InitThreads();
         ^
/astro/users/cchris28/projects/kbmod/lib/pybind11/include/pybind11/detail/internals.h:200:28: warning: ‘void PyEval_InitThreads()’ is deprecated (declared at /astro/users/cchris28/.conda/envs/kbmod/include/python3.10/ceval.h:122) [-Wdeprecated-declarations]
         PyEval_InitThreads();
                            ^
[100%] Linking CXX shared module search.cpython-310-x86_64-linux-gnu.so
[100%] Built target search
(kbmod) bash-4.2$

**Comment by jeremykubica** [comment]
Resolved with #217

**Comment by jeremykubica** [comment]
217 isn't actually merged yet. Reopening until that happens.

**Comment by DinoBektesevic** [comment]
It was on wait for me to test manual build with python 3.11. Closed in https://github.com/dirac-institute/kbmod/pull/217
