### ISSUE TITLE
calc_ecliptic_angle needs a test

### ISSUE THREAD

**Issue by jeremykubica** [dirac-institute/kbmod#228]
The function calc_ecliptic_angle needs a unit test.

**Comment by DinoBektesevic** [comment]
To me it was unclear what to test here. The function inputs are arbitrary so it's numerical output is not indicative of the fact that the function performs its intended purpose. See https://github.com/dirac-institute/kbmod/pull/167

**Comment by jeremykubica** [comment]
I'm not sure how to test this either. The goal of this function has never been clear to me. But if we are going to have this in the path of the main search (as it is now), then we should test that it is working as intended. Perhaps @jbkalmbach or @smotherh have enough context to help out here.

Alternatively we could remove this function and replace the logic for how we pick the center angle to search. I don't know what the best approach for that is though.

**Comment by jbkalmbach** [comment]
The goal of this function was to find a zero angle for our search by using a path parallel to the ecliptic as that. Then trajectories in our searches would be angles that crossed this path at +/- whatever your max angle for searching was. It is also useful as a way to make sure our trajectories are searching trajectories that move in the correct direction.

**Comment by jeremykubica** [comment]
Should we rename something like "calc_suggested_search_angle"?

**Comment by jbkalmbach** [comment]
That's fine with me. And if we want to open some research into what might be the best way to do this that might be a good idea from the science side.
