### ISSUE TITLE
KBMOD_Demo not working

### ISSUE THREAD

**Issue by ColinOrionChandler** [dirac-institute/kbmod#232]
Running KBMOD_Demo fails on the "Run KBMOD" cell. Traceback below.

The presence of "outimage2.fits" in data/demo breaks the string slicing used to extract image numbers. I'm wondering if this slicing is going to be trouble anyway with images not of this naming convention?

If I move the outimage2.fits out of the directory, the notebook runs without error end-to-end. Unclear what this file is for.

If outimage2.fits isn't needed, then can it be either removed or moved up one level?

Traceback:

ValueError                                Traceback (most recent call last)
Input In [14], in <cell line: 49>()
     20 input_parameters = {
     21     # Required
     22     "im_filepath": im_filepath,
   (...)
     45     "average_angle": 0.0,
     46 }
     48 rs = run_search(input_parameters)
---> 49 rs.run_search()

File ~/.conda/envs/kbmod_latest/lib/python3.10/site-packages/kbmod/run_search.py:241, in run_search.run_search(self)
    238 default_psf = kb.psf(self.config["psf_val"])
    240 # Load images to search
--> 241 stack, img_info, ec_angle = kb_interface.load_images(
    242     self.config["im_filepath"],
    243     self.config["time_file"],
    244     self.config["psf_file"],
    245     self.config["mjd_lims"],
    246     self.config["visit_in_filename"],
    247     default_psf,
    248 )
    250 # Set up the post processing data structure.
    251 kb_post_process = PostProcess(self.config, img_info.get_all_mjd())

File ~/.conda/envs/kbmod_latest/lib/python3.10/site-packages/kbmod/analysis_utils.py:105, in Interface.load_images(self, im_filepath, time_file, psf_file, mjd_lims, visit_in_filename, default_psf)
    103 for visit_file in np.sort(patch_visits):
    104     full_file_path = "{0:s}/{1:s}".format(im_filepath, visit_file)
--> 105     visit_str = str(int(visit_file[id_start:id_end]))
    107     # Check if we can prune the file based on the timestamp. We do this
    108     # before the file load to save time, but might have to recheck if the
    109     # time stamp is stored in the file itself.
    110     time_stamp = -1.0

ValueError: invalid literal for int() with base 10: 'outima'

**Comment by jeremykubica** [comment]
outimage2.fits isn't in the data/demo directory for the github repo, so I'm guessing that another script created this and didn't clean it up.  I haven't found which one yet, but will look. In the meantime, you can delete this.

In parallel, the loading function is a bit fragile and needs could use an upgrade. In the short term, I'll add some error checking.

**Comment by cchris28** [comment]
I verified that the existing of a data/demo/outimage2.fits no longer causes a failure. So closing
