### ISSUE TITLE
Implement convolution & searching on CPU for comparison/non-gpu support

### ISSUE THREAD

**Issue by PWhiddy** [dirac-institute/kbmod#24]
Implement searching code with C++ to run in parallel, for a more direct cpu/gpu comparison.

**Comment by jeremykubica** [comment]
Do we still need this? My feeling is that it would be interesting (but not critical) to see what speedup the GPU gives and we can probably get rid of this issue.

**Comment by jbkalmbach** [comment]
Yeah, I think this might have been something we thought would be nice for the first paper but is not something we need.
