### ISSUE TITLE
Investigate potential performance issues with stamp filtering.

### ISSUE THREAD

**Issue by DinoBektesevic** [dirac-institute/kbmod#295]
It was noted by Wesley Fraser that in dense fields stamp filtering takes a long time - on the order of 5h. 

It was also noted by him that searches looking for slow moving objects take significantly longer than those for fast moving ones. Even with image stacks that are half-depth than its faster-moving counter-parts. 

The version used in his processing is closer to v0.5.0 than the current one. 

I know a lot of works has been put in optimizing the performance of the detection code, and that this issue is one of continuous trade-offs between user-customizability versus black-box approach. 

PR https://github.com/dirac-institute/kbmod/pull/291 introduced new `cudaDeviceSynchronize` directives which reminded me that we should probably start making a note on whether or not such changes make an actually measurable differences, if so how large, or if they do not... 

Feel free to suggest appropriate selection of tests we might add to our per-PR, daily or weekly builds.

**Comment by jeremykubica** [comment]
I spent a while bench marking different approaches over the past few weeks and the GPU-based version currently implemented (but not in v0.5.0) is outperforming other methods. There are no obvious pending improvements. A different approach might be to do more filtering (or clustering) before generating the stamps.
