### ISSUE TITLE
Create a CPU version of co-added stamps

### ISSUE THREAD

**Issue by jeremykubica** [dirac-institute/kbmod#338]
Provide an option for generating the co-added stamps on CPU for systems without GPU.

**Comment by PWhiddy** [comment]
Small thought regrading cpu implementation -
functions can be qualified both `__device__` and `__host__` which should allow them to be called from both cpu and gpu. Factoring the current kernels into those functions could be a way to support cpu and gpu with minimal code duplication. 
You may already know this but just thought I'd mention it!

**Comment by jeremykubica** [comment]
That is a good point. We had been doing that on a bunch of functions previously. I had thought that you still needed the cuda toolkits to compile that code though. Is that the case? I am hoping to make it possible to install KBMOD on systems without it (for limited runs since it will be a lot more expensive without the GPU).

**Comment by PWhiddy** [comment]
Its true that you need the cuda toolkit to compile code using those, although you don't need a gpu to do just the compilation itself. However the cuda toolkit is still quite heavy and obviously you don't want to bring that around everywhere.
One option would be to conditionally apply the qualifiers with a macro, something like this:

```cuda
#include <iostream>

#ifdef __NVCC__
#define OPTIONAL_GPU_PREFIX __device__ __host__
#else
#define OPTIONAL_GPU_PREFIX
#endif

///////

OPTIONAL_GPU_PREFIX
int square_plus_one(int x) {
    return x * x + 1;
}

#ifdef __NVCC__
__global__ void square_plus_one_kernel(int* array, int n) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;
    if (tid < n)
        array[tid] = square_plus_one(tid);
}
#endif

int main(int argc, char *argv[])
{
    constexpr int N = 10;

#ifdef __NVCC__

    int ha[N];
    int *da;
    cudaMalloc((void **)&da, N*sizeof(int));
    square_plus_one_kernel<<<N, 1>>>(da, N);
    cudaMemcpy(ha, da, N*sizeof(int), cudaMemcpyDeviceToHost);
    cudaFree(da);

    std::cout << "GPU result" << "\n";
    for (int i = 0; i<N; ++i) {
        printf("%d\n", ha[i]);
    }
#endif

    std::cout << "CPU result" << "\n";
    
    for (int i = 0; i<N; ++i) {
        printf("%d\n", square_plus_one(i));
    }
 
    return 0;
}
```

https://godbolt.org/z/n7rnana4s

As a cpp file, this can be compiled by either nvcc or g++ (nvcc needs the flag `-x cu`, I'm not sure what the implications for cmake would be)

**Comment by jeremykubica** [comment]
Interesting. We went with a slightly different approach on an earlier such change (see the raw_image.cpp file in https://github.com/dirac-institute/kbmod/pull/337/files) that also used `#ifdef`, but in a different way. I hadn't thought about fully incorporating the GPU code into cpp files. Thanks for passing it along!
