### ISSUE TITLE
Break out input reading

### ISSUE THREAD

**Issue by jeremykubica** [dirac-institute/kbmod#355]
Restructure KBMOD's input reading to support multiple options (in preparation for the ImageCollection input). Define a general "read input" API (class or function signature) and move the current code out of `analysis_utils.py`.

**Comment by maxwest-uw** [comment]
will this be the read in for the new `ImageStack` or will this include the code to generate the stack?

**Comment by jeremykubica** [comment]
Neither yet. My thinking was to do this as a stage 1 for code cleanup. So the overall approach would look like:
1) Break out the current input loading code from `analysis_utils.py` into a standalone file with a clean interface for loading data. Preserve the current functionality of loading from a directory. **<< this change**
2) Create a `WorkUnit` class that encapsulates ALL in information needed for a full KBMOD run. The class should have readers and writers. **<< I'm working on this currently.**
3) Integrate the `WorkUnit` reading into the data loading file with the same interface (so that we can switch between the two for now).
4) Phase out the old directory loading code once we have the functionality to process different inputs and produce work units.

**Comment by jeremykubica** [comment]
I added a draft PR #368 to show what I am thinking for the `WorkUnit` class.

**Comment by jeremykubica** [comment]
Fixed in #371
