### ISSUE TITLE
Investigate why neither canary nor CI builds catch #385

### ISSUE THREAD

**Issue by DinoBektesevic** [dirac-institute/kbmod#386]
Failure to properly open a directory of files is not detected by the CI. Why

https://github.com/dirac-institute/kbmod/pull/385

**Comment by jeremykubica** [comment]
Your description about opening a directory of files doesn't match #385 which was about not closing files or reading alternate keys from the fits header correctly. Neither one caused an error in the types of files we currently use. Can you elaborate on what to investigate here?
