### ISSUE TITLE
Saving a layered_image doesn't overwrite an old one with the same name

### ISSUE THREAD

**Issue by jbkalmbach** [dirac-institute/kbmod#42]
It just adds extra layers without a warning in a jupyter notebook.

**Comment by jbkalmbach** [comment]
Did this get fixed @PWhiddy ?

**Comment by jeremykubica** [comment]
I checked this morning and the code still extra layers (instead of overwriting). I'm happy to fix this. To confirm is the desired behavior just to overwrite the old files?

**Comment by jbkalmbach** [comment]
Yeah, I think so. To be honest this was a long time ago and I'm not sure how often we are saving these any more but maybe they are useful for debugging.
