### ISSUE TITLE
Inconsistent checking of `NaN`s throughout the codebase

### ISSUE THREAD

**Issue by DinoBektesevic** [dirac-institute/kbmod#441]
There are a [couple of places](https://github.com/dirac-institute/kbmod/pull/334/files/c2ec4dca1e2b41c84c895767160ccf25e6dd947e#r1457964401) within the codebase where we define "empty" or "non-existing" values. NaNs are sometimes handled as existing values and sometimes as non-existing ones. It would be good to go through the codebase and make sure the way we handle NaNs is consistent.

**Comment by nemo-1999** [comment]
I would like to work on this issue

**Comment by nemo-1999** [comment]
I would like to work on this

**Comment by jeremykubica** [comment]
Sorry @nemo-1999, this ended up getting pulled into a larger set of changes. It will be addressed by a combination of #493 and #504.

**Comment by jeremykubica** [comment]
Closed by #504
