### ISSUE TITLE
Extend the PSF model to allow for a variable PSF (spatial and temporal)

### ISSUE THREAD

**Issue by connolly** [dirac-institute/kbmod#48]
PSF's can vary spatially and temporally. The PSF class should be able to account for this and the stack.convolve() should be able to take in a set of PSFs that are appropriate for each image in the stack

**Comment by jbkalmbach** [comment]
Based upon varying seeing in Lori Allen data we should have some way to at least change the Gaussian size over a series of images.

**Comment by jeremykubica** [comment]
If we can realistically expect 1 psf per image, then it would be easy to save the psf within the LayeredImage class. If a PSF has been assigned, the class would use that. Otherwise it can use a provided default. Would this address the request in this bug?

**Comment by jbkalmbach** [comment]
Yeah, I think that would work. We should have a PSF per image from the processed images.

**Comment by jbkalmbach** [comment]
And if nothing else we could create a Gaussian for each image based upon the seeing in each image.

**Comment by jeremykubica** [comment]
This was completed in an earlier PR
