### ISSUE TITLE
Add a mask trajectory function

### ISSUE THREAD

**Issue by jeremykubica** [dirac-institute/kbmod#500]
Add a function to `masking.py` that takes a trajectory, a `WorkUnit` or `ImageStack`, and radius then proceeds to add a mask to each image that is centered on the trajectory's predicted position and has the given radius. This can be used to support iterative search (remove the brightest objects first) or to remove stationary objects (with the upcoming `SingleVelocitySearch` generator in #485 and a setting of zero velocity).

**Comment by vlnistor** [comment]
Hi @jeremykubica, can I be assigned to this?

**Comment by jeremykubica** [comment]
closed by #515
