### ISSUE TITLE
Assess zero points / normalization (mosaic and temporal)

### ISSUE THREAD

**Issue by ColinOrionChandler** [dirac-institute/kbmod#667]
Three areas that should be in agreement:

1. Chip-to-chip for each timestep (mosaics)
2. Exposure-to-exposure (within a single night)
3. Night-to-night (for multi-night stacking)

The stack may be doing enough for this, but we should make sure (see also Pedro).

**Comment by DinoBektesevic** [comment]
I believe this is resolved by https://github.com/dirac-institute/kbmod/pull/671. Feel free to check and reopen if it isn't.
