### ISSUE TITLE
Unify the reflex motion of the Earth correction interface

### ISSUE THREAD

**Issue by DinoBektesevic** [dirac-institute/kbmod#699]
As discussed with Wilson and Colin, the reflex motion of the Earth correction code is in a bit of a state of dissaray with half a dozen implementations. They and I needed a fast vectorized implementation to make searchable collections which got merged in https://github.com/dirac-institute/kbmod/pull/669 without integration. 

This needs some cleanup, which can be deferred for a later date.

**Comment by jeremykubica** [comment]
I believe this was addressed by some of @maxwest-uw 's work, but feel free to re-open if this is still a problem.
